# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghrls < Formula
  desc "List & Describe GitHub Releases"
  homepage "https://github.com/dtan4/ghrls"
  version "0.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dtan4/ghrls/releases/download/v0.2.0/ghrls_Darwin_x86_64.tar.gz"
    sha256 "e3aacf07c61713475669868a475fd39f3ffe06f5ae840d3057a1df3f766fdd9c"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dtan4/ghrls/releases/download/v0.2.0/ghrls_Darwin_arm64.tar.gz"
    sha256 "ebed8c751e87d65e7d00dc594fc75d1433b6d35c35f1f17bf6af4144fd6be847"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dtan4/ghrls/releases/download/v0.2.0/ghrls_Linux_x86_64.tar.gz"
    sha256 "00096feb52d19a8bf45e903355280aa6dc5ac9f2fe67996e6d420935f54457af"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dtan4/ghrls/releases/download/v0.2.0/ghrls_Linux_armv6.tar.gz"
    sha256 "9e220106b26b9400a70c7c95421f75074d78f805f1d8aeb9652826a5540c88ac"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dtan4/ghrls/releases/download/v0.2.0/ghrls_Linux_arm64.tar.gz"
    sha256 "31db7d0aa36bf80a60550ae876c41138686e71539094d43c561c9938485c9075"
  end

  def install
    bin.install "ghrls"
  end

  test do
    system "#{bin}/s3url", "-v"
  end
end
