# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sec < Formula
  desc "CLI tool to manage Kubernetes Secrets easily"
  homepage "https://github.com/dtan4/k8sec"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dtan4/k8sec/releases/download/v0.8.0/k8sec_Darwin_arm64.tar.gz"
      sha256 "b4043cbac4f9114034a36fd8c7b9fa902a5c381ed11fc6b48aca959ae26515d1"

      def install
        bin.install "k8sec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dtan4/k8sec/releases/download/v0.8.0/k8sec_Darwin_x86_64.tar.gz"
      sha256 "564c32a9dd4471a7a1aaf43f15aa68926f19305de26e046742cfaefb6bb85575"

      def install
        bin.install "k8sec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dtan4/k8sec/releases/download/v0.8.0/k8sec_Linux_arm64.tar.gz"
      sha256 "8ce7aa376301e48e156b886ed91907eff5037ec16fbe3d0e6b27560cb519a588"

      def install
        bin.install "k8sec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dtan4/k8sec/releases/download/v0.8.0/k8sec_Linux_x86_64.tar.gz"
      sha256 "81e9908320d36c993113f46ad657d06f7daa5e965b56e607a6a96d4c22734f00"

      def install
        bin.install "k8sec"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dtan4/k8sec/releases/download/v0.8.0/k8sec_Linux_armv6.tar.gz"
      sha256 "6af1f133f9f89e65db1a4d67f981b63b2976cc40230617663f29fea3cc27e740"

      def install
        bin.install "k8sec"
      end
    end
  end

  test do
    system "#{bin}/k8sec", "version"
  end
end
