# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8stail < Formula
  desc "`tail -f` experience for Kubernetes Pods"
  homepage "https://github.com/dtan4/k8stail"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dtan4/k8stail/releases/download/v0.7.0/k8stail_Darwin_arm64.tar.gz"
      sha256 "09500f5f28b7fdabb04aa844e9758fbd2777ea02d1202da0a36a53bab473f665"

      def install
        bin.install "k8stail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dtan4/k8stail/releases/download/v0.7.0/k8stail_Darwin_x86_64.tar.gz"
      sha256 "10226cb887ea907892335cfd1b5c3c0ed3dcd86a2c981b7d9728bd80ed29bea1"

      def install
        bin.install "k8stail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dtan4/k8stail/releases/download/v0.7.0/k8stail_Linux_x86_64.tar.gz"
      sha256 "4f9e253e5f2ae0096d3b8a609194d8dfa1858d2285e5680faeecef12864ae5ed"

      def install
        bin.install "k8stail"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dtan4/k8stail/releases/download/v0.7.0/k8stail_Linux_armv6.tar.gz"
      sha256 "029e56589a78f8531fdb56413e29ba25105c2e5e660b132e7f2d1293fa8ca3ab"

      def install
        bin.install "k8stail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dtan4/k8stail/releases/download/v0.7.0/k8stail_Linux_arm64.tar.gz"
      sha256 "a43b5236bb7ec8d94fa8aa23e9504573e79aec4e13e64b0b521abca1ba923584"

      def install
        bin.install "k8stail"
      end
    end
  end

  test do
    system "#{bin}/k8stail", "-v"
  end
end
