# This file was generated by GoReleaser. DO NOT EDIT.
class S3url < Formula
  desc "Generate S3 object pre-signed URL in one command"
  homepage "https://github.com/dtan4/s3url"
  version "1.0.1-rc5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dtan4/s3url/releases/download/v1.0.1-rc5/s3url_Darwin_x86_64.tar.gz"
    sha256 "8aa6df2889502da673712b0054f62b1339ec1c0d66f8a57b9cc242063f95d0fb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dtan4/s3url/releases/download/v1.0.1-rc5/s3url_Linux_x86_64.tar.gz"
      sha256 "8ef6b0cf37c1ac4cd22777f0e222fe38d36dc6876ec1975a131f0a9f5f6dc098"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dtan4/s3url/releases/download/v1.0.1-rc5/s3url_Linux_arm64.tar.gz"
        sha256 "57f3ab130df14a433cb7b8d07d309ef14c462a274cd153d9550c7d3efaec9bbb"
      else
        url "https://github.com/dtan4/s3url/releases/download/v1.0.1-rc5/s3url_Linux_armv6.tar.gz"
        sha256 "01c1189a55d0dfe6415ac7561ee09934692c17f0eadd8ecb4501e573918326d6"
      end
    end
  end

  def install
    bin.install "s3url"
  end

  test do
    system "#{bin}/s3url", "-v"
  end
end
